apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "clamav.fullname" . }}-notify
  name: {{ include "clamav.fullname" . }}-notify
spec:
  ports:
  - name: {{ include "clamav.fullname" . }}-notify
    port: 80
    targetPort: 8080
  selector:
    name: {{ include "clamav.fullname" . }}-notify